export const MENTORING_EVIDENCE_BUCKET = 'mentoring-evidence';
export const MAX_MENTORING_EVIDENCE_COUNT = 3;
export const MAX_MENTORING_EVIDENCE_BYTES = 358400;
export const TARGET_MENTORING_EVIDENCE_BYTES = 307200;
export const MAX_MENTORING_EVIDENCE_DIMENSION = 1280;
export const MAX_MENTORING_EVIDENCE_INPUT_BYTES = 1024 * 1024;
export const MAX_MENTORING_EVIDENCE_SOURCE_BYTES = 10 * 1024 * 1024;
export const MENTORING_EVIDENCE_TRANSPORT_BYTES = 900 * 1024;
export const MENTORING_EVIDENCE_ALLOWED_INPUT_MIME = [
  'image/jpeg',
  'image/png',
  'image/webp',
] as const;

export const MENTORING_EVIDENCE_ACCEPT = MENTORING_EVIDENCE_ALLOWED_INPUT_MIME.join(',');
